/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
import java.awt.*;
import java.sql.*;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.*;
/**
 *
 * @author kenneth
 */
public class Login extends javax.swing.JFrame {

    /**
     * Creates new form Login
     */
    public Login() {
        initComponents();
        Connect();
    }
    
    Connection con;
    PreparedStatement pst;
    ResultSet rs;
    
    
    public void Connect(){
        
        try {
            //Open Connection to MySQL
            Class.forName("com.mysql.cj.jdbc.Driver");
            con = DriverManager.getConnection("jdbc:mysql://localhost:3306/users","root","");
            
        }catch(ClassNotFoundException ex){
            Logger.getLogger(Login.class.getName()).log(Level.SEVERE, null, ex);
            
        }catch(SQLException ex){
            Logger.getLogger(Login.class.getName()).log(Level.SEVERE, null, ex);

        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        bigPanel = new javax.swing.JPanel();
        smallPanel = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        emailTf = new javax.swing.JTextField();
        jSeparator1 = new javax.swing.JSeparator();
        passwordField = new javax.swing.JPasswordField();
        jSeparator2 = new javax.swing.JSeparator();
        logBtn = new javax.swing.JButton();
        signUp = new javax.swing.JLabel();
        forgetLbl1 = new javax.swing.JLabel();
        forgetLbl2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        imgPanel = new javax.swing.JPanel();
        colorPanel = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        imgLbl = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(1280, 720));
        setMinimumSize(new java.awt.Dimension(1280, 720));

        jPanel1.setMaximumSize(new java.awt.Dimension(1280, 720));
        jPanel1.setMinimumSize(new java.awt.Dimension(1280, 720));
        jPanel1.setPreferredSize(new java.awt.Dimension(1280, 720));
        jPanel1.setLayout(new java.awt.GridLayout(1, 0));

        bigPanel.setBackground(new java.awt.Color(49, 48, 77));
        bigPanel.setMaximumSize(new java.awt.Dimension(640, 720));
        bigPanel.setMinimumSize(new java.awt.Dimension(640, 720));
        bigPanel.setPreferredSize(new java.awt.Dimension(640, 720));

        smallPanel.setBackground(new java.awt.Color(22, 26, 48));
        smallPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Georgia Pro Cond Light", 0, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Sign In");
        jLabel1.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        smallPanel.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 61, 380, 72));

        emailTf.setBackground(new java.awt.Color(22, 26, 48));
        emailTf.setFont(new java.awt.Font("Georgia Pro Cond Light", 0, 18)); // NOI18N
        emailTf.setForeground(new java.awt.Color(204, 204, 204));
        emailTf.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        emailTf.setText("Email");
        emailTf.setBorder(null);
        smallPanel.add(emailTf, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 180, 247, 40));

        jSeparator1.setBackground(new java.awt.Color(255, 255, 255));
        jSeparator1.setForeground(new java.awt.Color(255, 255, 255));
        smallPanel.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 300, 250, 20));

        passwordField.setBackground(new java.awt.Color(22, 26, 48));
        passwordField.setFont(new java.awt.Font("Georgia Pro Cond Light", 0, 18)); // NOI18N
        passwordField.setForeground(new java.awt.Color(204, 204, 204));
        passwordField.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        passwordField.setText("Password");
        passwordField.setBorder(null);
        smallPanel.add(passwordField, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 260, 247, 40));

        jSeparator2.setBackground(new java.awt.Color(255, 255, 255));
        jSeparator2.setForeground(new java.awt.Color(255, 255, 255));
        smallPanel.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 220, 250, 20));

        logBtn.setBackground(new java.awt.Color(176, 100, 90));
        logBtn.setFont(new java.awt.Font("Georgia Pro", 0, 18)); // NOI18N
        logBtn.setForeground(new java.awt.Color(204, 204, 204));
        logBtn.setText("Log In");
        logBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logBtnActionPerformed(evt);
            }
        });
        smallPanel.add(logBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 330, 100, 40));

        signUp.setFont(new java.awt.Font("Georgia Pro Light", 1, 13)); // NOI18N
        signUp.setForeground(new java.awt.Color(204, 204, 204));
        signUp.setText("Sign Up");
        signUp.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                signUpMouseClicked(evt);
            }
        });
        smallPanel.add(signUp, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 460, 50, -1));

        forgetLbl1.setFont(new java.awt.Font("Georgia Pro Light", 0, 13)); // NOI18N
        forgetLbl1.setForeground(new java.awt.Color(204, 204, 204));
        forgetLbl1.setText("Forgot Password?");
        forgetLbl1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                forgetLbl1MouseClicked(evt);
            }
        });
        smallPanel.add(forgetLbl1, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 380, 110, -1));

        forgetLbl2.setFont(new java.awt.Font("Georgia Pro Light", 0, 13)); // NOI18N
        forgetLbl2.setForeground(new java.awt.Color(204, 204, 204));
        forgetLbl2.setText("Don't have an account?");
        smallPanel.add(forgetLbl2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 460, 130, -1));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imgs/icons8-lock-30.png"))); // NOI18N
        smallPanel.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 260, 30, 40));

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imgs/icons8-user-30.png"))); // NOI18N
        smallPanel.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 180, 30, 40));

        javax.swing.GroupLayout bigPanelLayout = new javax.swing.GroupLayout(bigPanel);
        bigPanel.setLayout(bigPanelLayout);
        bigPanelLayout.setHorizontalGroup(
            bigPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(bigPanelLayout.createSequentialGroup()
                .addGap(130, 130, 130)
                .addComponent(smallPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(130, Short.MAX_VALUE))
        );
        bigPanelLayout.setVerticalGroup(
            bigPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(bigPanelLayout.createSequentialGroup()
                .addGap(115, 115, 115)
                .addComponent(smallPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(105, 105, 105))
        );

        jPanel1.add(bigPanel);

        imgPanel.setBackground(new java.awt.Color(255, 255, 255));
        imgPanel.setMaximumSize(new java.awt.Dimension(640, 720));
        imgPanel.setMinimumSize(new java.awt.Dimension(640, 720));
        imgPanel.setName(""); // NOI18N
        imgPanel.setPreferredSize(new java.awt.Dimension(640, 720));
        imgPanel.setLayout(null);

        colorPanel.setBackground(new Color(49,48,77, 150));
        colorPanel.setMaximumSize(new java.awt.Dimension(640, 720));
        colorPanel.setMinimumSize(new java.awt.Dimension(640, 720));
        colorPanel.setPreferredSize(new java.awt.Dimension(640, 720));
        colorPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Georgia Pro Cond Semibold", 0, 36)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(204, 204, 204));
        jLabel2.setText("Welcome to Hotel De Furina");
        colorPanel.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 110, -1, -1));

        jLabel3.setFont(new java.awt.Font("Georgia Pro Semibold", 0, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(204, 204, 204));
        jLabel3.setText("Please enjoy your stay");
        colorPanel.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 150, 200, -1));

        imgPanel.add(colorPanel);
        colorPanel.setBounds(0, 0, 640, 720);

        imgLbl.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imgs/Sunset-City-iPhone-Wallpaper.jpg"))); // NOI18N
        imgLbl.setMaximumSize(new java.awt.Dimension(640, 720));
        imgLbl.setMinimumSize(new java.awt.Dimension(640, 720));
        imgLbl.setPreferredSize(new java.awt.Dimension(640, 720));
        imgPanel.add(imgLbl);
        imgLbl.setBounds(0, 0, 1280, 720);

        jPanel1.add(imgPanel);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void logBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logBtnActionPerformed
        // Login:
        //Gets the input from the text fields
        String email = emailTf.getText();
        String password = new String(passwordField.getPassword());
        String tableEmail = null;
        String tablePassword = null;
        try{
            // Selects the Usertable
            pst = con.prepareStatement("SELECT * FROM usertable WHERE email='"+email+"'");
            rs = pst.executeQuery();

            while(rs.next())
            {
                //Gets the email and password from the appropriate Column
                tableEmail = rs.getString("email");
                tablePassword = rs.getString("password");
            }
                //Checks if the user typed the correct login details
            if((email.equals("admin") && (password.equals("admin")))){
                //Redirects to the admin only page
                dispose();
            }else if((email.equals(tableEmail)) && (password.equals(tablePassword))){
                Room1 roomPage = new Room1();
                roomPage.show();
                dispose();
            }else{
                emailTf.setText("");
                passwordField.setText("");
                JOptionPane.showMessageDialog(this, "Email or Password is Incorrect");
                }
        }catch(SQLException ex){
            Logger.getLogger(Login.class.getName()).log(Level.SEVERE, null, ex); 
        }
    }//GEN-LAST:event_logBtnActionPerformed

    private void forgetLbl1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_forgetLbl1MouseClicked
        // Redirects to forgot page when clicked
        forgotPage forgotPage = new forgotPage();
        forgotPage.setVisible(true);
    }//GEN-LAST:event_forgetLbl1MouseClicked

    private void signUpMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_signUpMouseClicked
        // Redirects to sign up page when clicked
        signUp signUpPage = new signUp();
        signUpPage.show();
        dispose();
    }//GEN-LAST:event_signUpMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Login().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel bigPanel;
    private javax.swing.JPanel colorPanel;
    private javax.swing.JTextField emailTf;
    private javax.swing.JLabel forgetLbl1;
    private javax.swing.JLabel forgetLbl2;
    private javax.swing.JLabel imgLbl;
    private javax.swing.JPanel imgPanel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JButton logBtn;
    private javax.swing.JPasswordField passwordField;
    private javax.swing.JLabel signUp;
    private javax.swing.JPanel smallPanel;
    // End of variables declaration//GEN-END:variables
}
