
/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
import java.awt.*;
import javax.swing.*;

/**
 *
 * @author kenneth
 */
public class Main extends javax.swing.JFrame {

    /**
     * Creates new form Main
     */
    public Main() {
        initComponents();
        titleLbl.setHorizontalAlignment(JLabel.CENTER);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">
    private void initComponents() {

        imgPanel = new javax.swing.JPanel();
        colorPanel = new javax.swing.JPanel();
        titleLbl = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        loginBtn = new javax.swing.JButton();
        signBtn = new javax.swing.JButton();
        imgLbl = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(1280, 720));
        setMinimumSize(new java.awt.Dimension(1280, 720));

        imgPanel.setMaximumSize(new java.awt.Dimension(1280, 720));
        imgPanel.setMinimumSize(new java.awt.Dimension(1280, 720));
        imgPanel.setOpaque(false);
        imgPanel.setPreferredSize(new java.awt.Dimension(1280, 720));
        imgPanel.setLayout(null);

        colorPanel.setBackground(new Color(38, 80, 115, 110));
        colorPanel.setMaximumSize(new java.awt.Dimension(1280, 720));
        colorPanel.setMinimumSize(new java.awt.Dimension(1280, 720));

        titleLbl.setBackground(new java.awt.Color(255, 255, 255));
        titleLbl.setFont(new java.awt.Font("Ananda Black Personal Use", 0, 36)); // NOI18N
        titleLbl.setForeground(new java.awt.Color(255, 255, 255));
        titleLbl.setText("Hotel De Furina");

        jLabel1.setFont(new java.awt.Font("Lucida Sans Typewriter", 0, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("STAY ONCE, CARRY MEMORIES FOREVER");

        loginBtn.setBackground(new java.awt.Color(176, 100, 90));
        loginBtn.setFont(new java.awt.Font("Lucida Sans Unicode", 0, 18)); // NOI18N
        loginBtn.setForeground(new java.awt.Color(255, 255, 255));
        loginBtn.setText("Log In");
        loginBtn.setToolTipText("");
        loginBtn.setBorderPainted(false);
        loginBtn.setMargin(new java.awt.Insets(5, 14, 3, 14));
        loginBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loginBtnActionPerformed(evt);
            }
        });

        signBtn.setBackground(new java.awt.Color(176, 100, 90));
        signBtn.setFont(new java.awt.Font("Lucida Sans Unicode", 0, 18)); // NOI18N
        signBtn.setForeground(new java.awt.Color(255, 255, 255));
        signBtn.setText("Sign Up");
        signBtn.setToolTipText("");
        signBtn.setBorderPainted(false);
        signBtn.setDefaultCapable(false);
        signBtn.setMargin(new java.awt.Insets(5, 14, 3, 14));
        signBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                signBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout colorPanelLayout = new javax.swing.GroupLayout(colorPanel);
        colorPanel.setLayout(colorPanelLayout);
        colorPanelLayout.setHorizontalGroup(
                colorPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(colorPanelLayout.createSequentialGroup()
                                .addGap(453, 453, 453)
                                .addComponent(jLabel1)
                                .addContainerGap(457, Short.MAX_VALUE))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, colorPanelLayout.createSequentialGroup()
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(colorPanelLayout
                                        .createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING,
                                                colorPanelLayout.createSequentialGroup()
                                                        .addComponent(titleLbl, javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                275, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addGap(500, 500, 500))
                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, colorPanelLayout
                                                .createSequentialGroup()
                                                .addGroup(colorPanelLayout
                                                        .createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                        .addComponent(signBtn, javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                184, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addComponent(loginBtn, javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                184, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addGap(545, 545, 545)))));
        colorPanelLayout.setVerticalGroup(
                colorPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(colorPanelLayout.createSequentialGroup()
                                .addGap(76, 76, 76)
                                .addComponent(titleLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 66,
                                        javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 56,
                                        javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 248,
                                        Short.MAX_VALUE)
                                .addComponent(loginBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 46,
                                        javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(signBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 46,
                                        javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(158, 158, 158)));

        imgPanel.add(colorPanel);
        colorPanel.setBounds(0, 0, 1280, 720);

        imgLbl.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imgs/SkylineView.jpg"))); // NOI18N
        imgLbl.setMaximumSize(new java.awt.Dimension(1280, 720));
        imgLbl.setMinimumSize(new java.awt.Dimension(1280, 720));
        imgLbl.setPreferredSize(new java.awt.Dimension(1280, 720));
        imgPanel.add(imgLbl);
        imgLbl.setBounds(0, 0, 1280, 720);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addComponent(imgPanel, javax.swing.GroupLayout.PREFERRED_SIZE,
                                        javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE)));
        layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addComponent(imgPanel, javax.swing.GroupLayout.PREFERRED_SIZE,
                                        javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE)));

        pack();
    }// </editor-fold>

    private void loginBtnActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
        Login loginPage = new Login();
        loginPage.show();
        dispose();
    }

    private void signBtnActionPerformed(java.awt.event.ActionEvent evt) {
        // Add the signup redirect here
        signUp signUp = new signUp();
        signUp.show();
        dispose();
    }

    /**
     * @param args the command line arguments
     */

    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        // <editor-fold defaultstate="collapsed" desc=" Look and feel setting code
        // (optional) ">
        /*
         * If Nimbus (introduced in Java SE 6) is not available, stay with the default
         * look and feel.
         * For details see
         * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        // </editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Main().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify
    private javax.swing.JPanel colorPanel;
    private javax.swing.JLabel imgLbl;
    private javax.swing.JPanel imgPanel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JButton loginBtn;
    private javax.swing.JButton signBtn;
    private javax.swing.JLabel titleLbl;
    // End of variables declaration
}
